### PR TITLE
Update keymaps.cson

### PR DESCRIPTION
**Pull request by DeusProx**
make the keybindings only work on latex files!

### CODE REVIEW

**Comment by svkurowski** [comment]
I think it makes sense to have the keybindings trigger on other files, too.
Imagine I have a C file which I include in my Latex project using the `listings` package.
Now I make some changes in the C file and want to rebuild my pdf.
I don't want to switch to a latex file just to compile. So I think the current behaviour is fine.

**Comment by andrewrynhard** [comment]
I agree with @svkurowski. I think the activation of the package with the latex grammar is enough.

**Comment by DeusProx** [comment]
But shouldn't one then create extra keybinds for his special use case so not everyone else has to overwrite the default keybindings? Also for linux most of the existing keybinds didn't work out of the box. That's a future issue which should be adressed.

**Comment by andrewrynhard** [comment]
Are the keybindings activating when you are not working in the context of a 'Latex' project? Also which keybindings are not working?

**Comment by DeusProx** [comment]
@andrewrynhard With the current setting i can for example call the compile function on my small golang project which also produces an .latex directory and files in it. this shouldn't happen. And for me all of the specified keybindings didn't worked.

**Comment by andrewrynhard** [comment]
@DeusProx then `latex-plus` is not doing what it should. Or perhaps the package was activated and then you switched to the golang project? Regardless this should be fixed.

**Comment by DeusProx** [comment]
I just checked it.

Case a) Only Golang Project is open. Can't compile.
Case b) Golang-Project and Latex-Project are opened but no latex file was opened previously. Can't compile.
Case c) Golang-Project and one tex-file from another Latex-Project is open. Can compile go-file with latex-plus.

Will open another issue for the not working keybinds on linux.

**Pull request closed without merging**
